language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - ZEPHIR_VER=0.5.9
    - ZEPHIRDIR=/usr/local/src/zephir

before_script:
  - ./tests/ci/install.sh
  - ./tests/ci/prepare.sh
  - echo "extension=phelper.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: phpunit ./tests/

after_failure:
  - php -m
  - php --info
